### PR TITLE
Add provision to Github token secret for Github Actions

### PR DESCRIPTION
**Pull request by tejasync**
Add provision to Github token secret for Github Actions

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Let's try this. Thanks!

**Comment by escopecz** [comment]
Hmm, so this won't work. I got this error message when saving the secret:
```
Failed to add secret. Secret names must not start with GITHUB_
```

**Comment by tejasync** [comment]
I think we need to rename the key.

**Comment by tejasync** [comment]
PR to rename the secret: https://github.com/mautic/language-packer/pull/6

**Pull request merged**
